name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
            name: linux_amd64
          - os: windows-latest
            goos: windows
            goarch: amd64
            ext: ".exe"
            name: windows_amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            ext: ""
            name: darwin_amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            ext: ""
            name: darwin_arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build-only

    - name: Build docs
      run: npm run build:docs
      continue-on-error: true

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Go dependencies
      run: go mod download

    - name: Build binary
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      shell: bash
      run: |
        mkdir -p release
        go build -ldflags="-s -w" -o "release/ZhiKeFangZhou_${{ matrix.name }}${{ matrix.ext }}" server.go
        if [ -f "release/ZhiKeFangZhou_${{ matrix.name }}${{ matrix.ext }}" ]; then
          echo "✅ Build successful"
          ls -lh release/
        else
          echo "❌ Build failed"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ZhiKeFangZhou-${{ matrix.os }}-${{ matrix.goarch }}
        path: release/ZhiKeFangZhou_${{ matrix.name }}${{ matrix.ext }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Extract artifacts
      run: |
        echo "Artifacts structure:"
        find artifacts -type f -name "*" | head -20
        mkdir -p release
        # Copy all files from artifacts
        find artifacts -type f ! -name "*.md" ! -name "*.txt" -exec cp -v {} release/ \;
        echo "Release files:"
        find release -type f
        ls -lh release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/**
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
